- id: yarn_audit
  name: yarn_audit
  entry: bash
  language: node
  pass_filenames: false
  files: "^(yarn.lock|package.json)$"
  args: ["-c", "yarn audit || (sleep 60 && yarn audit) || (sleep 120 && yarn audit)"]
